server:
  port: 8888

spring:
  # 配置数据源信息
  datasource:
    dynamic:
      primary: u_classinfo
      strict: false
      datasource:
        # 配置数据源类型
        #    type: com.zaxxer.hikari.HikariDataSource
#        # 配置连接数据库的各个信息
#        uhelper:
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://localhost:3306/uhelper?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
#          username: root
#          password: 211314zzz

        u_classinfo:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/u_classinfo?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
          username: root
          password: 211314zzz

        u_courseinfo:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/u_courseinfo?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
          username: root
          password: 211314zzz

        u_graduateinfo:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/u_graduateinfo?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
          username: root
          password: 211314zzz

#        u_course_report:
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://localhost:3306/u_course_report?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
#          username: root
#          password: 211314zzz
  sa-token:
    # token名称 (同时也是cookie名称)
    token-name: token
    # token有效期，单位s 默认30天, -1代表永不过期
    timeout: 2592000
    # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
    activity-timeout: -1
    # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
    allow-concurrent-login: true
    # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
    is-share: false
    # token风格
    token-style: uuid



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  # 设置MyBatis-Plus的全局配置
  global-config:
    db-config:
      # 设置实体类所对应的表的统一前缀
      table-prefix:
      # 设置统一的主键生成策略
      id-type:
  # 配置类型别名所对应的包
  type-aliases-package: com.allspark.uhelper.db.pojo

#输出Log文件
logging:
  config: classpath:logback-spring.xml

springdoc:
  swagger-ui:
    # 修改Swagger UI路径
    path: /swagger-ui.html
    # 开启Swagger UI界面
    enabled: true
  api-docs:
    # 修改api-docs路径
    path: /v3/api-docs
    # 开启api-docs
    enabled: true

##自定义的枚举
#semester:
#  first:
#  second:
#  third:
#  fourth:

