server:
  port: 8080

spring:
  # 配置数据源信息
  datasource:
    dynamic:
      primary: uhelper
      strict: false
      datasource:
    # 配置数据源类型
    #    type: com.zaxxer.hikari.HikariDataSource
    # 配置连接数据库的各个信息
        uhelper:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/uhelper?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
          username: root
          password: 211314zzz

        u_classinfo:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/u_classinfo?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
          username: root
          password: 211314zzz

        u_courseinfo:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/u_courseinfo?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
          username: root
          password: 211314zzz

        u_graduateinfo:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/u_graduateinfo?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
          username: root
          password: 211314zzz

        u_course_report:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/u_course_report?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
          username: root
          password: 211314zzz



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  # 设置MyBatis-Plus的全局配置
  global-config:
    db-config:
      # 设置实体类所对应的表的统一前缀
      table-prefix:
      # 设置统一的主键生成策略
      id-type:
  # 配置类型别名所对应的包
  type-aliases-package: com.allspark.uhelper.domain

#输出Log文件
logging:
  config: classpath:logback-spring.xml


